### PR TITLE
MSVC compatibility

### PR DESCRIPTION
**Pull request by GregoryMorse**

### CODE REVIEW

**Comment by GregoryMorse** [comment]
M_PI is not defined in normal C.  _USE_MATH_DEFINES enables such extensions.  With cmath, including it first is important here, for more info https://stackoverflow.com/questions/6563810/m-pi-works-with-math-h-but-not-with-cmath-in-visual-studio

**Comment by GregoryMorse** [comment]
This should be ready for a merge.  Windows should use tbb12.lib not tbb.lib - so there was no need to introduce this extra variable.  But this should be enough to be compatible with MSVC.

Should we add some readme info?

**Comment by rakytap** [comment]
Would like to ask for some comments in readme to guide the user to install squander under windows

**Comment by GregoryMorse** [comment]
Many bugs, and standard compliance issues are fixed - likely should use -pedantic for gcc as it is too easy to break the builds in proper standard compliant C++11 with the lazy tolerances gcc allows...

**Comment by GregoryMorse** [comment]
2 general bugs fixed:
2 gsl dependencies were still present and removed
The interface to Problem for tolmin were inconsistent as the gradient should always have been a matrix_real& not a matrix_real.

Many other consistency and standard compliance issues.

**Comment by GregoryMorse** [comment]
This is gold now.  Should be ready for final merge.

But to maintain MSVC compatibility we should add pedantic restrictions on gcc to avoid easily introducing standards incompliance.  Not to mention gcc allows too flexible type inference which allows buggy code to build (and was inferring too much about BLAS).

**Comment by GregoryMorse** [comment]
All 57 tests pass on Windows.  python setup.py install likely works, but the manual instructions should be enough.  On my system, its an administrative restricted folder – even so tbb DLLs are not usually in the PATH (there isn’t a LD_LIBRARY_PATH on Windows) so they probably are best copied.

**Pull request merged**
