### PR TITLE
Further optimize sine/cosine calls in U3 gates

### PR DESCRIPTION
**Pull request by GregoryMorse**
Since theta/phi/lambda determine always zeroing cases - very common with CRY/RY gates and such, and such have trivial sine/cosine.  This may do very little on Linux if the glibc sin/cos already check zero cases, but that is implementation-dependent.

### CODE REVIEW

**Comment by rakytap** [comment]
Some tests, like qgd_python/decomposition/test/test_Compression.py are systematically failing with this commit.

**Comment by GregoryMorse** [comment]
Python (which presumably bears semblance to the C library/FPU function) shows that conceivable the sign of 0.0 is different...

```
>>> math.sin(0.0)
0.0
>>> math.sin(-0.0)
-0.0
>>> math.cos(-0.0)
1.0
>>> math.cos(0.0)
1.0
```

But that SQUANDER relies on sin(-0.0)==-0.0 is a bit questionable of not this code, but something else with another function or the test itself...  Its concerning likely and worth an investigation.

**Comment by rakytap** [comment]
Please try out the tests again. Sometimes one or two tests might fail, since the optimization is probabilistic.
On my end all the tests worked.

**Comment by GregoryMorse** [comment]
```
tests\decomposition\test_Compression.py ....                                                                     [  8%]
```

It is good to go, you are right it fails sometimes.

The test should be put in a loop and re-run and accepted if it passes in any number of iterations.  I think generally failure in <=1/2^64 or even better <=1/2^128 statistical probability is optimal for writing test cases, for best practice in unit tests.

sincos along with not doing it for the 0 cases (the check wastes a clock cycle vs saving hundreds of cycles), should actually be a reasonably decent improvement to have.

**Comment by GregoryMorse** [comment]
Annoyingly, Windows doesn't have a sincos in the C library, would have to get it via custom libraries, so just revert to the old behavior.

**Pull request merged**
