### PR TITLE
AVX instruction reduced variant of gate ops

### PR DESCRIPTION
**Pull request by GregoryMorse**
In theory double throughput, in practice around the same, should test on server hardware

### CODE REVIEW

**Comment by GregoryMorse** [comment]
Old code speeds (#qbits vs nanoseconds):
2 4440
3 23262
4 718240
5 631358
6 4411401
7 32554651
8 205200476

New code speeds:
2 3789
3 23562
4 687177
5 589095
6 4097745
7 30088014
8 196088078

**Comment by rakytap** [comment]
The latency and throughput of the individual instructions is different:

https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm256_mul_pd&ig_expand=4042,4042,5102,4042,5102&techs=AVX_ALL

Also, in my opinion you utilize more 256bit registers than it is available (16 in total), which migh be a source of slowdown as well. In overall, it is great you could improve uppon my solution :)

**Comment by GregoryMorse** [comment]
We should try it out with GCC on our Linux AMD servers though, probably similar results but we cant be sure yet.

**Comment by GregoryMorse** [comment]
Okay, so apparently gather's are terrible.  I used Visual Studio Profiler to see performance.  And 50% of the time is on the 4 gather instructions.  On StackOverflow, everyone is reporting its far better to read memory and use scalar instructions to swap or shuffle it around.  This solution might achieve much better throughput...will see.

**Comment by GregoryMorse** [comment]
An extra 4 shuffle didnt matter.  Gather is very slow.  Read unaligned is very fast.  Now 30% faster than the old version...  Its very significant!

New performance:
2 7289
3 26374
4 709178
5 452115
6 2861888
7 22160748
8 140212763

**Comment by GregoryMorse** [comment]
Ah I think its a bug...
`for (int col_idx = 0; col_idx < 2 * (input.cols - 1); col_idx = col_idx + 8) {`

Probably should be:
`for (int col_idx = 0; col_idx < 2 * (input.cols - 3); col_idx = col_idx + 8) {`

**Comment by GregoryMorse** [comment]
So there must be a bug in these two lines of code:

```
                if (input.cols % 4 != 0) {

                    for (int col_idx = input.cols - (input.cols % 4); col_idx < input.cols; col_idx++) {
```

As in the rectangular/too small cases, it falls back to this code...

But `2 % 4 != 0` is true and the loop goes through `0` and `1`...ahh thats the problem.  `1` is always the pair, it should only go through `0`.

I will fix it.

**Comment by GregoryMorse** [comment]
The bug is fixed...
`for (int col_idx = 0; col_idx < 2 * (input.cols - 1); col_idx = col_idx + 8) {`

Needed to be (or it would execute minimally one time always incorrectly):
`for (int col_idx = 0; col_idx < 2 * (input.cols - 3); col_idx = col_idx + 8) {`

**Comment by GregoryMorse** [comment]
Technically if the remaining columns is 2 or 3, we should reduce the next 2 columns out with the old method.  For a large rectangular matrix, that could be significant.  Kind of a hybrid/universal method combining the old and new one.

**Pull request merged**
