### PR TITLE
Reduce slow sine/cosine usage in U3 gates + bad AVX parallel heuristic

### PR DESCRIPTION
**Pull request by GregoryMorse**
sine/cosine require hundreds of clock cycles, while multiplication and addition require only a few.

### CODE REVIEW

**Comment by GregoryMorse** [comment]
The accuracy difference seems to be on a small order e.g. 1e-15.  The hardware sin/cos functions are actually very good approximations, but its worth noting this as the only potential downside.

**Comment by GregoryMorse** [comment]
Its unclear if gcc is using a custom sin/cos in the math library actually.  Regardless, multiplication and addition is cheaper.

If it uses hardware, here is an example on Intel Skylake for the micro-ops fused/latency (from https://www.agner.org/optimize/instruction_tables.pdf):
FSIN 53-105 50-120
FCOS 53-105 50-130
FSINCOS 55-120 55-150
F2XM1 16-90 65-80
FYL2X 40-100 103
FYL2XP1 56 77
FPTAN 40-112 140-160
FPATAN 30-160 100-160

load and store into the x87 for execution via FLD and FST are 1 clock cycle each from registers or non-segmented memory.

**Comment by rakytap** [comment]
I have failing build with:
/home/rakytap/Documents/software_testing/sequential-quantum-gate-decomposer/gates/U3.cpp: In member function ‘Matrix U3::calc_one_qubit_u3(double, double, double)’:
/home/rakytap/Documents/software_testing/sequential-quantum-gate-decomposer/gates/U3.cpp:555:25: error: ‘sin_Lambda’ was not declared in this scope
     u3_1qbit[1].imag = -sin_Lambda*sin_theta;

**Comment by GregoryMorse** [comment]
Sorry its fixed.  glibc on x86-64 does apparently use some SSE2-based library to do sin/cos and such.  x87 also has accuracy issues if not in range abs(x)<=3PI/4 for FSIN and abs(x)<=3PI/8 for FCOS.  I dont know about glibc, if the parameter range is an issue we should fmod(, 2*M_PI) on updates.

But square root being 1 clock cycle is at least very intriguing.  Even on FPGA, I think its not hard to implement.  Which is giving me some inspiration for e.g. Hafnians.  Division is more complex than square root though!  Who would have thought...

**Pull request merged**
