### PR TITLE
Fix crash issue in gradient only route

### PR DESCRIPTION
**Pull request by GregoryMorse**
The pointer to decomposition didnt need an extra reference (**).  Also the decrementing reference is invalid as no tuple created in this context.

### CODE REVIEW

**Comment by rakytap** [comment]
could you add a unit test for this functionality to avoid such issues in the future?

**Comment by GregoryMorse** [comment]
Yes we probably also should do the same for the new batched function as well - which we can include in this PR.

**Comment by GregoryMorse** [comment]
Just to note that Optimization_Problem_Batch is working.

**Comment by GregoryMorse** [comment]
Unit test added for consistency of get_Matrix, Optimization_Problem_Combined_Unitary, Optimization_Problem, Optimization_Problem_Batch, Optimization_Problem_Grad, Optimization_Problem_Combined

**Pull request merged**
